org: kerkerball
app: daily-chicken-soup
service: daily-chicken-soup
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  cronHandler:
    handler: src/handlers/createPost.run
    timeout: 120
    events:
      - schedule: cron(0 */12 ? * * *)